apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The application's http port.
    labels:
      application: openjdk-app
    name: openjdk-app
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: openjdk-app
- apiVersion: route.openshift.io/v1
  id: openjdk-app-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: openjdk-app
    name: openjdk-app
  spec:
    host: ""
    to:
      name: openjdk-app
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      application: openjdk-app
    name: openjdk-app
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      application: openjdk-app
    name: openjdk-app
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openjdk-app:latest
    source:
      contextDir: undertow-servlet
      git:
        ref: master
        uri: https://github.com/jboss-openshift/openshift-quickstarts
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: java:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: qMoY78MN
      type: GitHub
    - generic:
        secret: WP1Rotwq
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: openjdk-app
    name: openjdk-app
  spec:
    replicas: 1
    selector:
      deploymentConfig: openjdk-app
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: openjdk-app
          deploymentConfig: openjdk-app
        name: openjdk-app
      spec:
        containers:
        - env: []
          image: openjdk-app
          imagePullPolicy: Always
          name: openjdk-app
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - openjdk-app
        from:
          kind: ImageStreamTag
          name: openjdk-app:latest
      type: ImageChange
    - type: ConfigChange
kind: List
metadata: {}
